version: "3"

services:
  todo-app:
    build: .
    container_name: "todo-app"
    volumes:
      - "./:/root/todo-application"
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: "bash start.sh"
