# Generated by Django 2.2.1 on 2019-06-03 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('conditions', models.IntegerField(choices=[(1, '新規'), (2, '作業中'), (3, '完了')], default=1, verbose_name='状態')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
    ]
